-- REFERENCE / COMPATIBILITY ARTEFACT ONLY. DO NOT EXECUTE FOR STARTUP.
--
-- The old version of this file destructively dropped request and evidence tables.
-- The canonical, non-destructive schema is now the ordered migration set in
-- database/migrations/, applied by database/migrate.py and the Compose `migrate`
-- service. Generate schema snapshots from a migrated disposable database when a
-- standalone reference snapshot is required.
