'use client';
import { useEffect,useState } from 'react';
import { protectedFetch as fetch, shouldSuppressProtectedRequestError } from '@/lib/api-client';
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
interface Definition{workflow_key:string;display_name:string;description:string;category:string;built_in_handler:string;n8n_webhook_key:string|null;supports_schedule:boolean;required_task_keys:string[];required_connector_capabilities:string[];}
interface Preference{workflow_key:string;execution_mode:'built_in'|'n8n'|'hybrid'|'disabled';enabled:boolean;configuration:Record<string,unknown>;fallback_order:string[];schedule:Record<string,unknown>|null;}
export function WorkflowSettingsSection(){const[definitions,setDefinitions]=useState<Definition[]>([]),[preferences,setPreferences]=useState<Preference[]>([]);
 useEffect(()=>{fetch('/api/settings/workflows').then(r=>r.json()).then(data=>{setDefinitions(data.definitions||[]);setPreferences(data.preferences||[])}).catch(error=>{if(!shouldSuppressProtectedRequestError(error))toast.error('Could not load workflows')})},[]);
 const save=async(preference:Preference,execution_mode:Preference['execution_mode'])=>{try{const next={...preference,execution_mode,enabled:execution_mode!=='disabled',fallback_order:execution_mode==='hybrid'?['built_in','n8n']:[execution_mode==='n8n'?'n8n':'built_in']};const response=await fetch('/api/settings/workflows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const data=await response.json();if(!response.ok)return toast.error(data.message);setPreferences(current=>current.map(item=>item.workflow_key===preference.workflow_key?data.preference:item));toast.success('Workflow preference saved')}catch(error){if(!shouldSuppressProtectedRequestError(error))toast.error('Could not save workflow preference')}};
 return <Card><CardHeader><CardTitle>Workflows</CardTitle><CardDescription>Built-in is the normal path. N8N is an optional adapter selected per workflow.</CardDescription></CardHeader><CardContent className="space-y-3">{definitions.map(definition=>{const preference=preferences.find(p=>p.workflow_key===definition.workflow_key);if(!preference)return null;return <div key={definition.workflow_key} className="rounded-lg border p-3"><div className="flex flex-col gap-3 md:flex-row md:items-center"><div className="flex-1"><p className="font-medium">{definition.display_name}</p><p className="text-xs text-muted-foreground">{definition.description}</p></div><Select value={preference.execution_mode} onValueChange={value=>save(preference,value as Preference['execution_mode'])}><SelectTrigger className="w-full md:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="built_in">Built in</SelectItem>{definition.n8n_webhook_key&&<SelectItem value="n8n">N8N</SelectItem>}{definition.n8n_webhook_key&&<SelectItem value="hybrid">Hybrid</SelectItem>}<SelectItem value="disabled">Disabled</SelectItem></SelectContent></Select></div><p className="mt-2 text-xs text-muted-foreground">Status: {preference.enabled?'configured':'disabled'} · Uses: {definition.required_connector_capabilities.join(', ')||definition.required_task_keys.join(', ')||'built-in service'} · Schedule: {definition.supports_schedule?'configurable':'on demand'}</p>{(preference.execution_mode==='n8n'||preference.execution_mode==='hybrid')&&<p className="mt-2 rounded bg-muted p-2 text-xs">N8N webhook key: {definition.n8n_webhook_key}. Configure its URL in Advanced.</p>}</div>})}</CardContent></Card>}
