-- Compatibility marker only.
-- Operational schema changes are applied after PostgreSQL becomes healthy by
-- database/migrate.py from the ordered files in database/migrations/.
-- This file intentionally contains no application DDL.
